
/*
   날짜 : 2025/07/17
   이름 : 김수진
   내용 : 5장 데이터베이스 객체
*/
-- 워크북 P13
-- 실습하기
SELECT *FROM DICTIONARY;
SELECT TABLE_NAME FROM USER_TABLES;
SELECT OWNER, TABLE_NAME FROM ALL_TABLES;
// DBA로 시작하는 데이터 사전은 최고관리자SYSTEM만 조회가능함
SELECT * FROM DBA_TABLES;
SELECT * FROM DBA_USERS;

-- 실습하기 3-2
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;

-- 실습하기 3-3
// 인덱스 생성
CREATE INDEX IDX_USER1_ID ON USER1(USER_ID);
SELECT * FROM USER_IND_COLUMNS;

// DROP INDEX IDX_USER1_ID;
// SELECT * FROM USEER_IND_COLUMNS;

-- 실습하기 3-6
CREATE VIEW VW_USER1 AS (SELECT NAME, HP, AGE 
    FROM USER1);
CREATE VIEW VW_USER2_AGE_UNDER30 AS (SELECT * FROM
    USER2 WHERE AGE < 30);
SELECT * FROM USER_VIEWS;

SELECT * FROM VW_USER1;
SELECT * FROM VW_USER2_AGE_UNDER30;
DROP VIEW VW_USER1;    
DROP VIEW VW_USER2_AGE_UNDER30;   


-- 실습하기 3-9. 시퀀스 적용 테이블 생성
CREATE TABLE USER6 (
    SEQ NUMBER PRIMARY KEY,
    NAME VARCHAR2(20),
    GENDER CHAR(1),
    AGE NUMBER,
    ADDR VARCHAR2(255)
);
 
-- 실습하기3-10.시퀀스생성
CREATE SEQUENCE SEQ_USER6 INCREMENT BY 1 START WITH 1;   

INSERT INTO USER6 VALUES(SEQ_USER6.NEXTVAL,
    '김유신','M',25,'김해시');    
INSERT INTO USER6 VALUES (SEQ_USER6.NEXTVAL, 
    '김춘추', 'M', 23, '경주시');
INSERT INTO USER6 VALUES (SEQ_USER6.NEXTVAL, 
    '신사임당', 'F', 27, '강릉시');






