/*
   날짜 : 2025/07/17
   이름 : 김수진
   내용 : 5장 데이터베이스 객체
*/
-- 워크북 P13
-- 실습하기
SELECT *FROM DICTIONARY;
SELECT TABLE_NAME FROM USER_TABLES;
SELECT OWNER, TABLE_NAME FROM ALL_TABLES;
SELECT * FROM DBA_TABLES;
SELECT * FROM DBA_USERS;

SELECT INSTANCE_NAME, STATUS, DATABASE_STATUS, 
    HOST_NAME FROM V$INSTANCE;

-- 실습하기 4-1
// 오라클 12버전부터 바뀜
// 오라클에서 내부 스크립트 실행이나 일반 사용자 생성을
// 가능하게 하기 위한 세션 설정
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER TEST1 IDENTIFIED BY 1234;

-- 실습하기 4-2
SELECT * FROM ALL_USERS; // 전체 사용자 조회

-- 실습하시 4-3
ALTER USER TEST1 IDENTIFIED BY 1111;

-- 실습하기 4-4
GRANT CONNECT, RESOURCE TO TEST1;
GRANT UNLIMITED TABLESPACE TO TEST1;
// 이렇게 한번에 권한부여도 가능 
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO TEST1;














