create table customer (
    CID         VARCHAR2(20) PRIMARY KEY,
    NAME        VARCHAR2(20) NOT NULL,
    HP          CHAR(13) UNIQUE,
    ADDRESS     VARCHAR2(200),
    RDATE       DATE NOT NULL
);

-- 실습 1-3
insert into customer values ('c101', '김유신', '010-1234-1001', '김해시 봉황동', '2022-01-01');
insert into customer values ('c102', '김춘추', '010-1234-1002', '경주시 보문동', '2022-01-02');
insert into customer values ('c103', '장보고', '010-1234-1003', '완도군 청산면', '2022-01-03');
insert into customer values ('c104', '강감찬', '010-1234-1004', '서울시 마포구', '2022-01-04');
insert into customer values ('c105', '이성계', NULL, NULL, '2022-01-05');
insert into customer values ('c106', '정철', '010-1234-1006', '경기도 용인시', '2022-01-06');
insert into customer values ('c107', '허준', NULL, NULL, '2022-01-07');
insert into customer values ('c108', '이순신', '010-1234-1008', '서울시 영등포구', '2022-01-08');
insert into customer values ('c109', '송상현', '010-1234-1009', '부산시 동래구', '2022-01-09');
insert into customer values ('c111', '정약용', '010-1234-1011', '경기도 광주시', '2022-01-10');

rollback;

SELECT * FROM CUSTOMER;

commit;

CREATE TABLE FILES (
    NO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    oNAME VARCHAR2(200) NOT NULL,
    sNAME VARCHAR2(200) NOT NULL,
    rdate DATE  NOT NULL
);






