-- 교재 p26 ~ 64p까지
select * from emp;
DESC DEPT;
SELECT *FROM TAB;
SELECT EMPNO,ENAME FROM EMP;
SET PAGESIZE 15
SET LINESIZE 200
SELECT EMPNO, ENAME FROM EMP;

SET PAGESIZE 50
COL NAME FOR A20
SELECT NAME, 'GOOD MORNING~~!' "GOOD MORNING" FROM PROFESSOR;
SELECT DNAME, ',IT''S DEPTNO: ', DEPTNO "DNAME AND DEPTNO" FROM DEPT;
SELECT DNAME, Q'[,IT'S DEPTNO :]', DEPTNO "DNAME AND DEPTNO" FROM DEPT;
SELECT PROFNO, NAME, PAY FROM PROFESSOR;
SELECT PROFNO "PROF'SNO", NAME AS "PROF'S NAME", PAY PROF_PAY FROM PROFESSOR;

SELECT DEPTNO FROM EMP;
SELECT DISTINCT DEPTNO FROM EMP; // 중복제거
SELECT JOB, ENAME FROM EMP ORDER BY 1,2;
// SELECT JOB, ENAME FROM EMP ORDER BY JOB ASC, ENAME ASC;
// 이거랑 같은 의미임
// 기본이 ASC라서 DESC하려면 이렇게 해야됨
SELECT JOB, ENAME FROM EMP ORDER BY 1 DESC, 2 DESC;

SELECT ENAME, JOB FROM EMP;
SELECT ENAME || JOB FROM EMP;
SELECT ENAME ||'-'|| JOB FROM EMP;
SELECT 
  ENAME, 
  JOB,
  ENAME || JOB AS ENAME_JOB,
  ENAME || '-' || JOB AS ENAME_JOB_HYPHEN,
  ENAME ||' ''S JOB IS' ||JOB AS ENAME_S_JOB
FROM EMP;

SELECT EMPNO, ENAME FROM EMP WHERE EMPNO=7900;
SELECT ENAME, SAL FROM EMP WHERE SAL < 900;
SELECT EMPNO,ENAME, SAL FROM EMP WHERE ENAME='SMITH';
SELECT ENAME, HIREDATE FROM EMP WHERE ENAME ='SMITH';
SELECT EMPNO, ENAME, SAL FROM EMP WHERE HIREDATE = '80/12/17';

SELECT ENAME, SAL FROM EMP WHERE DEPTNO = 10;
SELECT ENAME, SAL, SAL*1.1 FROM EMP WHERE DEPTNO = 10;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL >= 4000;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME >= 'W';
// 문자비교연산자는 같은 문자형이여야지 비교가 된다.

SELECT ENAME, HIREDATE FROM EMP;
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE >= '81/12/25';
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL BETWEEN 2000 AND 3000;
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL >= 2000 AND SAL <= 3000;
SELECT EMPNO, ENAME, DEPTNO FROM EMP WHERE DEPTNO IN (10,20);
// 10번부서, 20번부서에 근무하는 사원의 SELECT
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL LIKE '1%';
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME LIKE 'A%';
SELECT EMPNO, ENAME, HIREDATE FROM EMP WHERE HIREDATE LIKE '80%';
// 위에 이거 작동안됨
SELECT EMPNO, ENAME, HIREDATE FROM EMP WHERE HIREDATE LIKE '___12%';
// SELECT EMPNO, ENAME, HIREDATE FROM EMP WHERE HIREDATE LIKE '__12%';

SELECT ENAME, HIREDATE, SAL FROM EMP WHERE HIREDATE > '82/01/01'
    AND SAL >= 1300;
SELECT ENAME, HIREDATE, SAL, COMM FROM EMP WHERE SAL > 1000
    AND (COMM < 1000 OR COMM IS NULL);







